Update bitrise script.

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,31 +1,35 @@
 ---
 format_version: 1.3.1
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
-trigger_map:
-- push_branch: main
-  workflow: deploy-to-github-pages
+trigger_map: []
 workflows:
   deploy-to-github-pages:
     steps:
-    - activate-ssh-key@4:
-        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone: {}
-    - script:
-        title: Install Jekyll
+    - apt-get-install@0.10.1:
         inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-            # See: https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html
-            sudo gem install bundler -v '2.2.2'
-            sudo bundle install
-    - script:
-        title: Deploy to Github Pages
+        - packages: ruby-full build-essential zlib1g-dev
+        title: Install Ruby using apt-get install
+    - script@1:
+        title: Build and Deploy Website
         inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-            bundle exec rake deploy
+        - content: |
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
+
+            # Install Jekyll and its dependencies
+            bundle install
+
+            # Build and deploy the website
+            bundle exec rake bitrise_deploy
+    triggers:
+      push:
+      - branch: main
 meta:
   bitrise.io:
     stack: linux-docker-android-22.04
